version: '3.8'
services:
  db:
    container_name: postgres_study
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./postgres_init/setup.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local